name: Swift Package CI

on:
  push:
    branches:
      - feature/semantic_type
  pull_request:
    branches:
      - feature/semantic_type

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.0.3"
      # Install Swift (usually pre-installed on macOS runners)
      - name: Ensure Swift version
        run: swift --version

      # Build the package
      - name: Build Swift package
        run: swift build --disable-sandbox

      - name: Install Doppler CLI
        uses: dopplerhq/cli-action@v3

      # Run tests
      - name: Run tests
        run: make test
        env:
          UMLSCLIENT_UPCOMING_FEATURES: SemanticType
          DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
          DOPPLER_CONFIG: ${{ secrets.DOPPLER_CONFIG }}
          DOPPLER_ENVIRONMENT: ${{ secrets.DOPPLER_ENVIRONMENT }}
          DOPPLER_PROJECT: ${{ secrets.DOPPLER_PROJECT  }}
          UMLS_API_KEY: ${{ secrets.UMLS_API_KEY }}
          UMLS_HOST: ${{ secrets.UMLS_HOST }}
          UMLS_VERSION: ${{ secrets.UMLS_HOST  }}
          UMLS_PAGE_CONTENT_SIZE: ${{ secrets.UMLS_PAGE_CONTENT_SIZE }}
